In [ ]:
# Numpy (Numerical Python)
# foundation of entire Python data science
#Scikitlearn, pandas, tenserflow -> they all use Numpy under the hood

# The core idea: Numpy is like a Pyhon list
#            Much faste: operations run in compiled C, not python
#            Much less memory: stores data more efficiently
#            Mathematical operations: add, multiply, average

import numpy as np

In [13]:
print(np.__version__)

2.1.3


In [ ]:
# CREATING ARRAYS : Numpy's core data structure
# can create using np.array()
# can be 1D (single row, like a column of data) and 2D (rows and cols, like a spreadsheet) or higher
# key properties array has:
#                         .shape() -> dimensions(rows,cols)
#                         .dtype() -> data type(int64, float64, ......)
#                         .ndim() -> number of dimensions
#                         .size() -> total numbers of elements

#1D array

scores = np.array([88,23,45,43,56])
print(scores.shape)
print(scores.dtype)
print(scores.ndim)
print(scores.size)

(5,)
int64
1
5


In [28]:
#Useful crators

zeros = np.zeros(5)
print(zeros)

ones = np.ones((2,3))
print(ones)

rng = np.arange(0,10,2)
print(rng)

rng = np.arange(0,100,3)
print(rng)

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


In [15]:
#2D array (3 rows, 2 columns)

matrix = np.array([[1,2],[3,4],[5,6]])
print(matrix.shape)
print(matrix)

(3, 2)
[[1 2]
 [3 4]
 [5 6]]


In [16]:
# 3D array
import numpy as np

matrix = np.array([[[1,1,1],[2,2,2],[3,3,3]]])
print(matrix)
print(matrix.shape)
print(matrix.ndim)
print(matrix.dtype)
print(matrix.size)

[[[1 1 1]
  [2 2 2]
  [3 3 3]]]
(1, 3, 3)
3
int64
9


In [33]:
# array of six studens scores

scores = np.array([88,89,59,60,89,99])

print(scores.shape)
print(scores.dtype)
print(scores.size)

# 2D array of shape 3,3

matrix = np.ones((3,3))
print(matrix)

matrix = np.zeros((3,3))
print(matrix)

(6,)
int64
6
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [41]:
# Array operations
# doing maths on entire attay at once.
# with numpy you can write array + 10 like operations that applies to every element automatically which is called as vectorization
# vectorized operation are 10 - 100x faster than python loops. This is why all ML libraries are built on Numpy.

scores = np.array([88,89,90,56,78,77])

#Operations on every element at once

print(scores + 10)
print(scores *2)
print(scores /10)
print(scores **2)

# operation between two arrays

a= np.array([1,2,3])
b = np.array([5,6,7])

print(a+b)
print(a *b)


[ 98  99 100  66  88  87]
[176 178 180 112 156 154]
[8.8 8.9 9.  5.6 7.8 7.7]
[7744 7921 8100 3136 6084 5929]
[ 6  8 10]
[ 5 12 21]


In [52]:
# creating an array of 5 temperature in celsius

temp_cels = np.array([37,40,34,35,39])

temp_farh = (temp_cels * 9/5 +32)

print(temp_cels)
print(f"Temperature in farhenheit:", np.round(temp_farh,1))

[37 40 34 35 39]
Temperature in farhenheit: [ 98.6 104.   93.2  95.  102.2]


In [ ]:
# ARRAY INDEXING AND SLICING
# accessing rows, cols and subsets
# indexing numpy array works like Python list for 1D, but 2D arrays use [rows, cols] syntax which is more powerful

# Boolean indexing is especially important for data work, it lets you filter an array based on a condition, just like database WHERE clause. This is exacly what Pandas uses under the hood
# Boolean indexing is one of the most used patterns in all of data analytics. Master it here and Pandas will feel completely natural

scores = np.array([88,89,99,85,34,43,55])

# Basic indexing (Same as lists)

print(scores[1])
print(scores[0:4])
print(scores[-1])
print("\n")

# Bolean indexing - filter by condition

print(scores[scores>80])
print(scores[scores<50])
print("\n")

# 2D array indexing 

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
print(matrix[1, 0])  # (row 1, col 0)
print(matrix[:, 1])  # [2,5,8] (all rows, cols)
print(matrix[1, :])  # [4,5,6] (rows1, all cols)


89
[88 89 99 85]
55


[88 89 99 85]
[34 43]


[[1 2 3]
 [4 5 6]
 [7 8 9]]
4
[2 5 8]
[4 5 6]


In [76]:
# creating an array of 8 exam scors

scores = np.array([88,89,67,45,47,99,50,77])

print(f"Scores above 75 are: {scores[scores>75]}")

print(f"Scores between 60 and 80 are: {scores[(scores>60) & (scores<80)]}")

Scores above 75 are: [88 89 99 77]
Scores between 60 and 80 are: [67 77]


In [81]:
# STATISTICAL FUNCTIONS
# summarising data in one line
# Numpy has all the statistical funciton you need for data analytics built right in. These work on the whole array or along a specific axis (rows or cols) in 2D arrays
# these are the exact same calucations Pandas use when you call .describe() on a DataFrame, so understanding them here makes everyhting click later.
# NOTE: axis = 0 means operate doen each column
#       axis = 1 means operate across each row.
# this trips up a lot of beginners - draw it out if confused

data = np.array([88, 72, 95, 61, 79, 84])

print(np.mean(data))
print(np.median(data))
print(np.std(data))
print(np.min(data))
print(np.max(data))
print(np.sum(data))
print("\n")

# on 2D array - axis=0 mean per column
marks = np.array([[80,90],[70,85],[95,78]])
print(np.mean(marks, axis = 0))
print(np.mean(marks, axis =1))

79.83333333333333
81.5
11.036555420762204
61
95
479


[81.66666667 84.33333333]
[85.  77.5 86.5]


In [91]:
# array of 10 randomish numbers of your choice

numbers = np.random.randint(1,11, size=10)
print(numbers)

print(f"The mean of random numbers: {np.mean(numbers)}")
print(f"The median of random numbers: {np.median(numbers)}")
print(f"The standard deviation of random numbers: {np.std(numbers)}")
print(f"The minimum of random numbers: {np.min(numbers)}")
print(f"The maximum of random numbers: {np.max(numbers)}")
print(f"The sum of random numbers: {np.sum(numbers)}")

print(f"Numbers greater than the mean: {numbers[numbers > np.mean(numbers)]}")


[10  9  1  3  4  5  7  9  8  3]
The mean of random numbers: 5.9
The median of random numbers: 6.0
The standard deviation of random numbers: 2.947880594596735
The minimum of random numbers: 1
The maximum of random numbers: 10
The sum of random numbers: 59
Numbers greater than the mean: [10  9  7  9  8]


In [ ]:
# Putting it together
# a mini data analysis with numpy
# this is almost exactly what happens inside Pandas when you load and summarise a dataset/
# if possible push to git
# NOTE: Get into habit of pushing after every lession/ Your Github contribution graph will start filling up - thats your portfolio growing in real time

# simulate student exam data

maths = np.array([88, 72, 95, 61, 79, 84, 53, 91])
science = np.array([92, 85, 90, 70, 80, 88, 60, 94])

# stack into 2D: rows = students and cols= subjects

all_marks = np.array([maths, science]).T
print(all_marks)
print("Shape:", all_marks.shape)

# average per subject

avg = np.mean(all_marks, axis=0)
print(f"The average marks of subject are: {avg}")

#average per student

avg_per_student = np.mean(all_marks, axis=1)
print(f"The average marks of each student are: {avg_per_student}")

# Who passed?

passed = avg_per_student[avg_per_student>=75]
print(f"The students who passed are: {passed}")
print(f"Passed: {len(passed)}/{len(avg_per_student)} students")

# top scorer index

print(f"The top score index is: {np.argmax(avg_per_student)}")


[[88 92]
 [72 85]
 [95 90]
 [61 70]
 [79 80]
 [84 88]
 [53 60]
 [91 94]]
Shape: (8, 2)
The average marks of subject are: [77.875 82.375]
The average marks of each student are: [90.  78.5 92.5 65.5 79.5 86.  56.5 92.5]
The students who passed are: [90.  78.5 92.5 79.5 86.  92.5]
Passed: 6/8 students
The top score index is: 2


In [ ]:
maths = np.random.randint(1,100, size =10)
science = np.random.randint(1,100, size =10)

all_marks = np.array([maths, science]).T
print(all_marks)

avg_sub = np.average(all_marks, axis=0)
print(f"The average marks of subject are: {avg_sub }")

avg_std = np.average(all_marks, axis=1)
print(f"The average marks of student are: {avg_std}")

lowest_score = np.argmin(avg_std)
print(f"The lowest score index is: {lowest_score}")

greater_80 = maths[maths>80]
print(f"The scores greater than 80  in mathsare: {greater_80}")

per = len([greater_80])/len(maths)*100
print(f"The percentage of students who scored greater than 80 in maths is: {per}%")





[[96 77]
 [59 60]
 [60 60]
 [41 33]
 [37 10]
 [93 48]
 [ 1 96]
 [11 71]
 [87 65]
 [15 56]]
The average marks of subject are: [50.  57.6]
The average marks of student are: [86.5 59.5 60.  37.  23.5 70.5 48.5 41.  76.  35.5]
The lowest score index is: 4
The scores grater than 80  in mathsare: [96 93 87]
The percentage of students who scored greater than 80 in maths is: 10.0%


: 